version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    day: "friday"
    time: "17:00"
    timezone: "America/Chicago"
  reviewers:
    - "pshrest2"
  groups:
    npm-deps:
      patterns:
        - "*"
      update-types:
        - "patch"
        - "minor"

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "17:00"
    timezone: "America/Chicago"
  reviewers:
    - "pshrest2"
  groups:
    bundler-dev-deps:
      dependency-type: "development"
      update-types:
        - "patch"
        - "minor"
    bundler-prod-deps:
      dependency-type: "production"
      update-types:
        - "patch"
        - "minor"
